sudo: required

services:
    - docker
before_install:
    - docker build -t reneshankar/react-test -f ./client/Dockerfile.dev ./client

script: 
    #- docker run rene/react-test npm test -- --coverage
    - docker run -e CI=true reneshankar/react-test npm run test

after_success:
    - docker build -t reneshankar/multi-client ./client
    - docker build -t reneshankar/multi-nginx ./nginx
    - docker build -t reneshankar/multi-server ./server
    - docker build -t reneshankar/multi-worker ./worker

    # Login to docker CLI
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub.
    - docker push reneshankar/multi-client
    - docker push reneshankar/multi-nginx
    - docker push reneshankar/multi-server
    - docker push reneshankar/multi-worker
    



